/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package Jframe;

//import java.sql.Connection;

import java.sql.PreparedStatement;
import java.sql.Connection;
import javax.swing.JOptionPane;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;



/**
 *
 * 
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    public Register() {
        initComponents();
        setTitle("Register"); // Menambahkan judul aplikasi
        //Agar txt_contact hanya menginput number
        txt_contact.addKeyListener(new KeyAdapter() {
    @Override
    public void keyTyped(KeyEvent e) {
        char c = e.getKeyChar();
        if (!Character.isDigit(c)) { // Memeriksa apakah karakter bukan angka
            e.consume(); // Mengabaikan keystroke jika bukan angka
        }
    }
});

        
    }
    
    
    
    
    
    public boolean isValidEmail(String email) {
    String regex = "^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$";
    return email.matches(regex);
    
    }

    //validateSignUp
    public boolean validateSigUp(){
        String username = txt_username.getText();
        String email = txt_email.getText();
        String password = txt_password.getText();
        String contact = txt_contact.getText();
        
        if (username.equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter username");
            return false;
        }
        
        if (email.equals("@")) {
            JOptionPane.showMessageDialog(this, "Please enter email format '@' correctly");
            return false;
        }
        if (password.equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter password");
            return false;
        }
        if (contact.equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter your number contact");
            return false;
        }
         return true;
    }

    //methode to insert values into users table
    public void insertSignUp(){
        String username = txt_username.getText();
        String email = txt_email.getText();
        String password = txt_password.getText();
        String contact = txt_contact.getText();


        try {
            
            Connection con = (Connection) DBConnection.getConnection();
            String sql = "INSERT INTO users(username,email,password,contact) VALUES (?,?,?,?)";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, username);
            pst.setString(2, email);
            pst.setString(3, password);
            pst.setString(4, contact);
        
            
            int updatedRowCount = pst.executeUpdate();
          
            if (updatedRowCount > 0){
                JOptionPane.showMessageDialog(this, "Register Successfully, Please Login!");   
                LogIn page = new LogIn();
                page.setVisible(true);
                dispose();
            }else{
                JOptionPane.showMessageDialog(this, "Please enter username or E-mail Correctly"); 
            }
            

        } catch (Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jdl_email = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        jdl_username = new javax.swing.JLabel();
        jdl_contact = new javax.swing.JLabel();
        txt_contact = new javax.swing.JTextField();
        button_signup = new javax.swing.JButton();
        txt_password = new javax.swing.JPasswordField();
        jdl_password = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        button_signup1 = new javax.swing.JButton();
        jdl_contact3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 102, 102));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jdl_email.setBackground(new java.awt.Color(0, 0, 0));
        jdl_email.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jdl_email.setText("E-mail");
        getContentPane().add(jdl_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 50, 20));

        txt_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usernameActionPerformed(evt);
            }
        });
        getContentPane().add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 270, 30));

        jdl_username.setBackground(new java.awt.Color(0, 0, 0));
        jdl_username.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jdl_username.setText("Username");
        getContentPane().add(jdl_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, -1, 20));

        jdl_contact.setBackground(new java.awt.Color(0, 0, 0));
        jdl_contact.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jdl_contact.setText("No. HP");
        getContentPane().add(jdl_contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, -1, 20));

        txt_contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_contactActionPerformed(evt);
            }
        });
        getContentPane().add(txt_contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, 270, 30));

        button_signup.setBackground(new java.awt.Color(204, 204, 255));
        button_signup.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        button_signup.setText("Register");
        button_signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_signupActionPerformed(evt);
            }
        });
        getContentPane().add(button_signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 520, 120, 30));

        txt_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_passwordActionPerformed(evt);
            }
        });
        getContentPane().add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 270, 30));

        jdl_password.setBackground(new java.awt.Color(0, 0, 0));
        jdl_password.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jdl_password.setText("Password");
        getContentPane().add(jdl_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, -1, 20));

        txt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailActionPerformed(evt);
            }
        });
        getContentPane().add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 270, 30));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 255));
        jLabel10.setText("Registrasi");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, -1, -1));

        button_signup1.setBackground(new java.awt.Color(102, 102, 255));
        button_signup1.setText("Log In");
        button_signup1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_signup1MouseClicked(evt);
            }
        });
        button_signup1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_signup1ActionPerformed(evt);
            }
        });
        jPanel1.add(button_signup1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 570, 80, 30));

        jdl_contact3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jdl_contact3.setText("Sudah Punya Akun?");
        jPanel1.add(jdl_contact3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 570, -1, -1));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 1, 30)); // NOI18N
        jLabel8.setText("Sistem Pendaftaran Mahasiswa");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 650));

        setSize(new java.awt.Dimension(534, 654));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usernameActionPerformed
        // TODO add your handling code here:
        validateSigUp();
    }//GEN-LAST:event_txt_usernameActionPerformed

    private void txt_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_passwordActionPerformed
        // TODO add your handling code here:
        validateSigUp();
    }//GEN-LAST:event_txt_passwordActionPerformed

    private void button_signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_signupActionPerformed
   String email = txt_email.getText();
boolean isValid = isValidEmail(email);

if (isValid) {
    // Lanjutkan proses sign up
    // ...
    insertSignUp();
} else {
    JOptionPane.showMessageDialog(this, "Invalid email address");
}

        
        
        
 
    }//GEN-LAST:event_button_signupActionPerformed

    private void txt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailActionPerformed
        // TODO add your handling code here:
        validateSigUp();
    }//GEN-LAST:event_txt_emailActionPerformed

    private void txt_contactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_contactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_contactActionPerformed

    private void button_signup1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_signup1ActionPerformed

    }//GEN-LAST:event_button_signup1ActionPerformed

    private void button_signup1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_signup1MouseClicked
        // TODO add your handling code here:
        LogIn log = new LogIn();
        log.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_button_signup1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_signup;
    private javax.swing.JButton button_signup1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel jdl_contact;
    private javax.swing.JLabel jdl_contact3;
    private javax.swing.JLabel jdl_email;
    private javax.swing.JLabel jdl_password;
    private javax.swing.JLabel jdl_username;
    private javax.swing.JTextField txt_contact;
    private javax.swing.JTextField txt_email;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables

    private void Connect() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void setIconImage() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
